### ISSUE TITLE
Commenting a line does not work

### ISSUE THREAD

**Issue by fho** [kthibodeaux/pull-review#17]
I'm trying to create a comment for a line with the plugin.
After I opened a PR I'm pressing 'c' on a line that changed in the diff view, enter a comment in the scratch window, close the scratch window with `:q`.

The comment does not show up in the PR.
I also do not get any feedback from the plugin if commenting succeeded or failed

**Comment by kthibodeaux** [comment]
I don't have the best mappings by default, nor amazing documentation.  Sorry about that!

To post a comment, leave insert mode and press enter.

**Comment by fho** [comment]
That worked! :-)
Thanks a lot for the quick help
